### ISSUE TITLE
Potential Buddy List Fragment

### ISSUE THREAD

**Issue by sgzsh269** [fit360/spott#2]
- Use User model and Activity model to process information and show a list of potential buddy users based on common activity interests, location and time
- Each list item has the user's profile image, name, age, gender and 2 top activities with respective location and times and a button to send a `interested` request to the user
- Ability to filter based on activity, location, time

**Comment by adilansari** [comment]
@sgzsh269 I will work on backend for this. Basically, this is what I'll do:
- Implement `List<Activity> getMatchingActivities()` in `Activity` model. 
  - This will be a generic filter based on location and type of activity, initially.
  - Later on, we can improve the same raw method.

Once this is done, I can work on a listview or something to display that.
