### ISSUE TITLE
Profile, Tracking and Parse Backend

### ISSUE THREAD

**Issue by sgzsh269** [fit360/spott#5]
- Setup Profile Activity based on User model
- Setup Tracking Activity based on Track model
- Setup Parse Backend and coordinate with @adilansari on the full setup

**Comment by adilansari** [comment]
Hi @aparnarsjain ,
Are you implementing the user profile layout as a part of this?

**Comment by aparnarsjain** [comment]
Yes, I implemented some basic blocks of the profile, need to wire it with
the data now.

On Sun, Mar 6, 2016 at 12:47 PM, Adil Ansari notifications@github.com
wrote:

> Hi @aparnarsjain https://github.com/aparnarsjain ,
> Are you implementing the user profile layout as a part of this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fit360/spott/issues/5#issuecomment-192987090.

## 

Thanks,

Aparna
